# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  facebook_key: 228717563963082
  facebook_secret: 89c191fcd96199bee99f18579b2f4892
  google_id: 775592490782.apps.googleusercontent.com
  google_secret: fXw-B9t4kwGTY5gMYpyiszgx
  secret_key_base: 6419c15139af2d7cbfb6e52ccdcd644b3e3be34802264bd2a189ab80bd3189bf275778f72fdd99bdba82f1e1dc7821c1b7dd989ae76446798572097022e0531b

test:
  secret_key_base: 3bcec19df9761bd303ebb245628cac0dcf1da5711533fb4041f78c8ba3575bef0aba02b12a8f0c4db190913610f37c4d0fb7a8c94c392a8d42f0000f202c1e94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  facebook_key: 228717563963082
  facebook_secret: 89c191fcd96199bee99f18579b2f4892
  google_id: 775592490782.apps.googleusercontent.com
  google_secret: fXw-B9t4kwGTY5gMYpyiszgx
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
